name: BrandedBySam
favicon: null
layout_spectrum: 0.2953741957899183
typography_spectrum: 0.5274065881967545
title: Branded By Sam
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#011023'
    - '#368ece'
    - '#196aa9'
    - '#79caff'
    - '#dcf2fd'
  brandStrength: 0.125
  lightness: 0.5625
  saturation: 0.125
  rhythmicContrast: 0.25
purpose: []
